services:
  - type: web
    name: api-selenium-render
    env: docker
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/chromium
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
